Repository cmu-db/peloton, pull requests merged in 2018-06, with the labels that each got.

#1384 Move tile group related code from catalog manager to storage manager
  src/catalog/manager.cpp
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_manager.cpp
  src/executor/delete_executor.cpp
  src/executor/hybrid_scan_executor.cpp
  src/executor/index_scan_executor.cpp
  src/executor/update_executor.cpp
  src/gc/transaction_level_gc_manager.cpp
  src/include/catalog/manager.h
  src/include/storage/storage_manager.h
  src/main/tpcc/tpcc_workload.cpp
  src/main/ycsb/ycsb_workload.cpp
  src/statistics/backend_stats_context.cpp
  src/storage/data_table.cpp
  src/storage/storage_manager.cpp
  src/storage/tile_group.cpp
  test/catalog/manager_test.cpp
  test/executor/testing_executor_util.cpp
  test/storage/tile_group_test.cpp
Labels: accepted

#1391 Minor Cleanup Timer + DeleteSQLTests
  src/include/common/timer.h
  test/executor/create_index_test.cpp
  test/executor/delete_test.cpp
  test/executor/update_test.cpp
  test/sql/delete_sql_test.cpp
  test/sql/testing_sql_util.cpp
Labels: accepted

#1389 LLVM 5.0 and 6.0 compatibility
  src/codegen/codegen.cpp
  src/codegen/function_builder.cpp
  src/udf/udf_parser.cpp
Labels: accepted

#1335 Enable tests with Address Sanitizer for Mac builds on Travis (#1315)
  .travis.yml
  script/installation/packages.sh
Labels: accepted, build

#1329 Run clang-format on staged hunks only instead of whole file
  script/formatting/formatter.py
  script/helpers.py
Labels: ready_for_review

#1406 Resolve Protobuf early exit
  script/installation/packages.sh
Labels: ready_for_review

#1400 Fix warning for unused lambda capture on Clang 9.1
  test/codegen/csv_scan_translator_test.cpp
Labels: accepted

#1408 Fix HashTable::BuildLazy if it contains zero emelemts
  src/codegen/util/hash_table.cpp
  test/codegen/hash_table_test.cpp
Labels: bug, ready_for_review

#1401 RWSet performance fixes, LockFreeArray performance fixes and tests
  src/common/container/lock_free_array.cpp
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_context.cpp
  src/include/common/container/lock_free_array.h
  src/include/concurrency/transaction_context.h
  test/common/lock_free_array_test.cpp
Labels: accepted

#1383 Catalog updates for checkpoints
  src/catalog/catalog.cpp
  src/catalog/catalog_cache.cpp
  src/catalog/column_catalog.cpp
  src/catalog/index_catalog.cpp
  src/catalog/layout_catalog.cpp
  src/catalog/system_catalogs.cpp
  src/catalog/table_catalog.cpp
  src/executor/drop_executor.cpp
  src/include/catalog/catalog_cache.h
  src/include/catalog/catalog_defaults.h
  src/include/catalog/column_catalog.h
  src/include/catalog/database_catalog.h
  src/include/catalog/index_catalog.h
  src/include/catalog/language_catalog.h
  src/include/catalog/proc_catalog.h
  src/include/catalog/schema_catalog.h
  src/include/catalog/table_catalog.h
  src/include/catalog/trigger_catalog.h
  src/include/storage/data_table.h
  src/include/storage/layout.h
  src/storage/data_table.cpp
  src/storage/layout.cpp
  src/tuning/layout_tuner.cpp
  test/catalog/catalog_test.cpp
  test/codegen/table_scan_translator_test.cpp
  test/executor/drop_test.cpp
  test/sql/drop_sql_test.cpp
  test/tuning/layout_tuner_test.cpp
Labels: ready_for_review

#1412 Remove unused rpc component.
  src/include/network/service/abstract_message.h
  src/include/network/service/connection_manager.h
  src/include/network/service/message_queue.h
  src/include/network/service/network_address.h
  src/include/network/service/peloton_client.h
  src/include/network/service/peloton_endpoint.h
  src/include/network/service/peloton_service.h
  src/include/network/service/rpc_channel.h
  src/include/network/service/rpc_client.h
  src/include/network/service/rpc_controller.h
  src/include/network/service/rpc_method.h
  src/include/network/service/rpc_server.h
  src/include/network/service/rpc_type.h
  src/include/network/service/rpc_utils.h
  src/include/network/service/tcp_connection.h
  src/include/network/service/tcp_listener.h
  src/network/service/connection_manager.cpp
  src/network/service/network_address.cpp
  src/network/service/peloton_service.cpp
  src/network/service/rpc_channel.cpp
  src/network/service/rpc_client.cpp
  src/network/service/rpc_server.cpp
  src/network/service/rpc_utils.cpp
  src/network/service/tcp_connection.cpp
  src/network/service/tcp_listener.cpp
  test/network/network_address_test.cpp
  test/network/rpc_client_test.cpp
  test/network/rpc_queryplan_test.cpp
  test/network/rpc_server_test.cpp
Labels: accepted

#1418 Network Layer Refactor
  src/include/common/notifiable_task.h
  src/include/network/connection_dispatcher_task.h
  src/include/network/connection_handle.h
  src/include/network/connection_handle_factory.h
  src/include/network/connection_handler_task.h
  src/include/network/marshal.h
  src/include/network/network_io_wrapper_factory.h
  src/include/network/network_io_wrappers.h
  src/include/network/network_state.h
  src/include/network/peloton_rpc_handler_task.h
  src/include/network/peloton_server.h
  src/include/network/postgres_protocol_handler.h
  src/include/network/protocol_handler.h
  src/include/network/protocol_handler_factory.h
  src/network/README
  src/network/connection_dispatcher_task.cpp
  src/network/connection_handle.cpp
  src/network/connection_handler_task.cpp
  src/network/marshal.cpp
  src/network/network_io_wrapper_factory.cpp
  src/network/network_io_wrappers.cpp
  src/network/peloton_server.cpp
  src/network/postgres_protocol_handler.cpp
  src/network/protocol_handler.cpp
  src/network/protocol_handler_factory.cpp
  test/network/exception_test.cpp
  test/network/prepare_stmt_test.cpp
  test/network/select_all_test.cpp
  test/network/simple_query_test.cpp
  test/network/ssl_test.cpp
Labels: ready_for_review

#1423 TileGroupHeader refactor
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/gc/transaction_level_gc_manager.cpp
  src/include/concurrency/timestamp_ordering_transaction_manager.h
  src/include/storage/tile_group_header.h
  src/storage/tile_group_header.cpp
Labels: ready_for_review

#1425 Skip adding READs to the RWSet
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_context.cpp
  src/include/concurrency/transaction_context.h
Labels: ready_for_review

#1426 Inline tuple SpinLatch after TileGroupHeader refactor
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/include/storage/tile_group_header.h
  src/storage/tile_group_header.cpp
Labels: ready_for_review

#1244 Bytecode Interpreter
  cmake/Dependencies.cmake
  cmake/Modules/FindLibffi.cmake
  script/installation/packages.sh
  src/codegen/code_context.cpp
  src/codegen/codegen.cpp
  src/codegen/compilation_context.cpp
  src/codegen/interpreter/bytecode_builder.cpp
  src/codegen/interpreter/bytecode_function.cpp
  src/codegen/interpreter/bytecode_interpreter.cpp
  src/codegen/query.cpp
  src/codegen/updateable_storage.cpp
  src/executor/plan_executor.cpp
  src/include/codegen/code_context.h
  src/include/codegen/codegen.h
  src/include/codegen/interpreter/bytecode_builder.h
  src/include/codegen/interpreter/bytecode_function.h
  src/include/codegen/interpreter/bytecode_instructions.def
  src/include/codegen/interpreter/bytecode_interpreter.h
  src/include/codegen/proxy/proxy.h
  src/include/codegen/query.h
  src/include/codegen/query_compiler.h
  src/include/common/macros.h
  src/include/common/overflow_builtins.h
  src/include/settings/settings.h
  src/include/util/math_util.h
  test/codegen/bloom_filter_test.cpp
  test/codegen/bytecode_interpreter_test.cpp
  test/codegen/function_builder_test.cpp
  test/codegen/if_test.cpp
  test/codegen/testing_codegen_util.cpp
  test/codegen/value_integrity_test.cpp
  test/common/overflow_builtins_test.cpp
  test/include/codegen/testing_codegen_util.h
Labels: accepted, feature

#1385 Apply limit + order optimization in the optimizer
  src/include/optimizer/operators.h
  src/include/planner/order_by_plan.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rule_impls.cpp
  src/planner/order_by_plan.cpp
Labels: accepted

#1429 Set LastReaderCommitId on new versions
  src/concurrency/timestamp_ordering_transaction_manager.cpp
Labels: accepted, bug

#1434 fix #1386: PerformVectorizedRead optimization
  src/codegen/operator/table_scan_translator.cpp
  src/codegen/proxy/transaction_runtime_proxy.cpp
  src/codegen/transaction_runtime.cpp
  src/include/codegen/proxy/transaction_runtime_proxy.h
  src/include/codegen/transaction_runtime.h
Labels: accepted, bug, enhancement

#1436 Fix ssl copy bug
  src/network/network_io_wrapper_factory.cpp
Labels: accepted
