Repository cmu-db/peloton, pull requests merged in 2018-02, with the labels that each got.

#1143 Clean up of the index utility code
  src/include/index/bwtree.h
  src/include/index/bwtree_index.h
  src/include/index/compact_ints_key.h
  src/include/index/generic_key.h
  src/include/index/index.h
  src/include/index/index_util.h
  src/include/index/tuple_key.h
  src/index/bwtree_index.cpp
  src/index/index_util.cpp
  test/index/testing_index_util.cpp
Labels: accepted, cleanup

#1148 Fix order-by in codegen
  src/codegen/codegen.cpp
  src/codegen/operator/order_by_translator.cpp
  src/codegen/type/bigint_type.cpp
  src/codegen/type/decimal_type.cpp
  src/codegen/type/type_system.cpp
  src/include/codegen/codegen.h
  test/sql/order_by_sql_test.cpp
Labels: accepted, bug

#1142 Support Ubuntu 17.10
  CMakeLists.txt
  script/installation/packages.sh
  src/include/common/exception.h
  src/include/index/sorted_small_set.h
  src/include/type/value_factory.h
Labels: ready_for_review

#1157 Fix duplicated headers
  src/network/peloton_server.cpp
  src/network/postgres_protocol_handler.cpp
  src/network/protocol_handler.cpp
  src/network/service/network_address.cpp
Labels: accepted

#1140 fix building under Fedora 27
  Jenkinsfile
  script/docker/fedora27/Dockerfile
  script/docker/fedora27/Dockerfile-jenkins
  script/installation/packages.sh
Labels: accepted

#1160 Fix create index
  src/executor/create_executor.cpp
Labels: accepted, bug

#1139 Rpc and thread infrastructure
  src/include/capnp/peloton_service.capnp
  src/include/common/dedicated_thread_owner.h
  src/include/common/dedicated_thread_registry.h
  src/include/common/dedicated_thread_task.h
  src/include/network/network_thread.h
  src/include/network/peloton_rpc_handler_task.h
  src/include/network/peloton_server.h
  src/include/settings/settings.h
  src/include/threadpool/mono_queue_pool.h
  src/main/peloton/peloton.cpp
  src/network/connection_handle.cpp
  src/network/peloton_server.cpp
Labels: accepted

#1172 Fix hook bypass command
  script/git-hooks/pre-commit
Labels: accepted

#1155 ensure that the dependencies for jdbc_validator.py are installed
  Jenkinsfile
Labels: accepted

#1163 Clear insert plan value_ vector after use. Fixes issue #1151.
  src/executor/plan_executor.cpp
  src/include/executor/plan_executor.h
  src/include/planner/abstract_plan.h
  src/include/planner/insert_plan.h
Labels: accepted
