Repository cmu-db/peloton, pull requests merged in 2018-03, with the labels that each got.

#1177 Fix the -fPIC flag setting for external projects.
  cmake/External/capnproto.cmake
  cmake/External/gflags.cmake
  cmake/External/glog.cmake
Labels: accepted

#1180 changes requested in #1169
  Jenkinsfile
  script/docker/centos7/Dockerfile
  script/docker/centos7/Dockerfile-jenkins
  script/installation/packages.sh
Labels: ready_for_review

#1179 Modify init.cpp to fetch connection_thread_count setting
  src/common/init.cpp
  src/include/settings/settings.h
Labels: accepted

#1138 Small code cleanups
  src/common/init.cpp
  src/common/internal_types.cpp
  src/include/catalog/abstract_catalog.h
  src/include/common/internal_types.h
  src/network/peloton_server.cpp
  src/storage/data_table.cpp
  src/storage/temp_table.cpp
Labels: accepted

#1105 Information about indexes affected by a given query
  src/include/catalog/catalog_cache.h
  src/include/parser/insert_statement.h
  src/include/parser/sql_statement.h
  src/include/parser/update_statement.h
  src/include/planner/plan_util.h
  src/include/util/set_util.h
  src/planner/plan_util.cpp
  test/planner/plan_util_test.cpp
  test/util/set_util_test.cpp
Labels: in progress

#1182 Refactor original brain files out into separate folder
  src/common/init.cpp
  src/include/concurrency/transaction_context.h
  src/include/storage/data_table.h
  src/include/storage/tile_group_header.h
  src/include/tuning/brain_util.h
  src/include/tuning/clusterer.h
  src/include/tuning/index_tuner.h
  src/include/tuning/layout_tuner.h
  src/include/tuning/sample.h
  src/main/peloton/peloton.cpp
  src/main/sdbench/sdbench_workload.cpp
  src/storage/data_table.cpp
  src/tuning/clusterer.cpp
  src/tuning/index_tuner.cpp
  src/tuning/layout_tuner.cpp
  src/tuning/sample.cpp
  test/brain/query_logger_test.cpp
  test/settings/settings_manager_test.cpp
  test/tuning/brain_util_test.cpp
  test/tuning/clusterer_test.cpp
  test/tuning/index_tuner_test.cpp
  test/tuning/layout_tuner_test.cpp
  third_party/capnproto/doc/_posts/2013-08-12-capnproto-0.2-no-more-haskell.md
  third_party/libpg_query/src/postgres/src_backend_libpq_pqcomm.c
Labels: accepted

#1150 Support for Join reordering
  src/include/common/internal_types.h
  src/include/optimizer/operator_node.h
  src/include/optimizer/rule_impls.h
  src/optimizer/binding.cpp
  src/optimizer/group.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/memo.cpp
  src/optimizer/operator_node.cpp
  src/optimizer/operators.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/optimizer_task.cpp
  src/optimizer/rule.cpp
  src/optimizer/rule_impls.cpp
  test/optimizer/optimizer_rule_test.cpp
  test/optimizer/optimizer_test.cpp
Labels: accepted

#1127 Lint Python files and port them to Python3
  .travis.yml
  Jenkinsfile
  script/formatting/formatter.py
  script/git-hooks/pre-commit
  script/helpers.py
  script/validators/source_validator.py
  script/validators/stat_validator.py
Labels: accepted

#1147 Add unnesting for correlated subquery in where clause with aggregation
  src/binder/bind_node_visitor.cpp
  src/common/internal_types.cpp
  src/expression/aggregate_expression.cpp
  src/include/common/internal_types.h
  src/include/expression/aggregate_expression.h
  src/include/expression/expression_util.h
  src/include/optimizer/operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/query_to_operator_transformer.h
  src/include/optimizer/rule.h
  src/include/optimizer/rule_impls.h
  src/include/optimizer/util.h
  src/include/planner/abstract_scan_plan.h
  src/include/planner/aggregate_plan.h
  src/include/planner/seq_scan_plan.h
  src/optimizer/input_column_deriver.cpp
  src/optimizer/operators.cpp
  src/optimizer/optimizer_task.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rule.cpp
  src/optimizer/rule_impls.cpp
  src/optimizer/util.cpp
  src/planner/aggregate_plan.cpp
  test/codegen/group_by_translator_test.cpp
  test/codegen/query_cache_test.cpp
  test/sql/optimizer_sql_test.cpp
  test/sql/testing_sql_util.cpp
Labels: accepted

#1159 Tensorflow Integration - Step 1
  .gitignore
  cmake/Dependencies.cmake
  cmake/ProtoBuf.cmake
  script/installation/packages.sh
  src/CMakeLists.txt
  src/brain/modelgen/LSTM_Model.py
  src/brain/modelgen/model_generator.py
  src/brain/modelgen/settings.json
  src/include/brain/tf_util.h
  test/brain/tensorflow_util_test.cpp
Labels: accepted, build

#1134 Use Cuckoohash instead of std::unordered_map to keep track of the ReadWriteSet
  src/common/container/cuckoo_map.cpp
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_context.cpp
  src/include/common/container/cuckoo_map.h
  src/include/common/internal_types.h
  src/include/common/item_pointer.h
  src/include/concurrency/transaction_context.h
Labels: accepted

#1200 Modify StatsStorage::GetTableStats() to take a txn as a parameter instead creating a new one
  src/binder/binder_context.cpp
  src/include/optimizer/cost_calculator.h
  src/include/optimizer/optimizer_metadata.h
  src/include/optimizer/stats/stats_storage.h
  src/include/optimizer/stats_calculator.h
  src/optimizer/cost_calculator.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/optimizer_task.cpp
  src/optimizer/stats/stats_storage.cpp
  src/optimizer/stats_calculator.cpp
  test/optimizer/selectivity_test.cpp
  test/optimizer/stats_storage_test.cpp
Labels: accepted

#1088 Fix uncaught conversion error
  src/include/type/value_factory.h
  test/sql/insert_sql_test.cpp
Labels: accepted

#1210 Fix for #1209, packages.sh failures on Ubuntu Xenial
  script/installation/packages.sh
Labels: accepted

#1213 Minimal fix for "make check", #1196
  src/include/optimizer/optimizer.h
  test/optimizer/optimizer_rule_test.cpp
Labels: accepted

#1208 Initial Junit JDBC tests
  .gitignore
  script/testing/junit/InsertPSTest.java
  script/testing/junit/InsertTPCCTest.java
  script/testing/junit/PLTestBase.java
  script/testing/junit/Readme.txt
Labels: accepted

#1158 Support for optimizer task execution timeouts
  src/include/common/exception.h
  src/include/optimizer/group.h
  src/include/optimizer/optimize_context.h
  src/include/optimizer/optimizer.h
  src/include/optimizer/optimizer_metadata.h
  src/include/settings/settings.h
  src/optimizer/group.cpp
  src/optimizer/optimizer.cpp
  src/settings/settings_manager.cpp
  test/include/optimizer/mock_task.h
  test/include/parser/mock_sql_statement.h
  test/optimizer/optimizer_test.cpp
Labels: accepted

#1218 SSL handshake refactor
  src/include/common/internal_types.h
  src/include/network/connection_handle.h
  src/include/network/connection_handle_factory.h
  src/include/network/marshal.h
  src/include/network/network_state.h
  src/include/network/postgres_protocol_handler.h
  src/include/network/protocol_handler.h
  src/network/connection_handle.cpp
  src/network/postgres_protocol_handler.cpp
  src/network/protocol_handler.cpp
  test/network/ssl/root_test.crt
  test/network/ssl/server_test.crt
  test/network/ssl/server_test.key
  test/network/ssl_test.cpp
Labels: accepted

#1206 Query Clustering
  src/brain/cluster.cpp
  src/brain/kd_tree.cpp
  src/brain/query_clusterer.cpp
  src/include/brain/cluster.h
  src/include/brain/kd_tree.h
  src/include/brain/query_clusterer.h
  test/brain/query_clusterer_test.cpp
  third_party/annoy/LICENSE
  third_party/annoy/annoylib.h
  third_party/annoy/kissrandom.h
  third_party/annoy/mman.h
Labels: accepted

#1185 Modify CreateDropObjectSet to use tbb::concurrent_vector
  cmake/Dependencies.cmake
  cmake/Modules/FindTBB.cmake
  script/installation/packages.sh
  src/executor/aggregator.cpp
  src/executor/index_scan_executor.cpp
  src/executor/merge_join_executor.cpp
  src/executor/order_by_executor.cpp
  src/include/common/container_tuple.h
  src/include/common/internal_types.h
  src/include/concurrency/transaction_context.h
  src/include/executor/aggregator.h
  src/include/expression/constant_value_expression.h
  src/include/index/generic_key.h
  src/include/index/tuple_key.h
  src/include/storage/zone_map_manager.h
  src/include/type/type_util.h
  src/include/type/value.h
  src/index/index.cpp
  src/index/index_util.cpp
  src/optimizer/stats/cost.cpp
  src/storage/tuple.cpp
  src/storage/zone_map_manager.cpp
  src/type/array_type.cpp
  src/type/boolean_type.cpp
  src/type/date_type.cpp
  src/type/decimal_type.cpp
  src/type/integer_parent_type.cpp
  src/type/timestamp_type.cpp
  src/type/varlen_type.cpp
  test/binder/binder_test.cpp
  test/codegen/block_nested_loop_join_translator_test.cpp
  test/codegen/case_translator_test.cpp
  test/codegen/group_by_translator_test.cpp
  test/codegen/hash_join_translator_test.cpp
  test/codegen/insert_translator_test.cpp
  test/codegen/order_by_translator_test.cpp
  test/codegen/parameterization_test.cpp
  test/codegen/query_cache_test.cpp
  test/codegen/table_scan_translator_test.cpp
  test/codegen/update_translator_test.cpp
  test/codegen/zone_map_scan_test.cpp
  test/common/container_tuple_test.cpp
  test/common/lock_free_array_test.cpp
  test/executor/aggregate_test.cpp
  test/executor/materialization_test.cpp
  test/executor/seq_scan_test.cpp
  test/expression/expression_test.cpp
  test/logging/recovery_test.cpp
  test/parser/postgresparser_test.cpp
  test/storage/masked_tuple_test.cpp
  test/storage/temp_table_test.cpp
  test/type/array_value_test.cpp
  test/type/boolean_value_test.cpp
  test/type/date_value_test.cpp
  test/type/numeric_value_test.cpp
  test/type/timestamp_value_test.cpp
  test/type/type_util_test.cpp
  test/type/value_factory_test.cpp
  test/type/value_test.cpp
Labels: accepted

#1226 Fix wrong return type in codegen Decimal::CompareGtImpl
  src/codegen/type/decimal_type.cpp
Labels: accepted, bug

#1207 Tensorflow Integration: Step 2
  src/brain/tf_session_entity/tf_session_entity.cpp
  src/brain/tf_session_entity/tf_session_entity_input.cpp
  src/brain/tf_session_entity/tf_session_entity_io.cpp
  src/brain/tf_session_entity/tf_session_entity_output.cpp
  src/include/brain/tf_session_entity/tf_session_entity.h
  src/include/brain/tf_session_entity/tf_session_entity_input.h
  src/include/brain/tf_session_entity/tf_session_entity_io.h
  src/include/brain/tf_session_entity/tf_session_entity_output.h
  src/include/brain/tf_util.h
  src/include/util/file_util.h
  test/brain/tensorflow_test.cpp
Labels: accepted

#1215 Add access methods to optimizer tests
  src/include/optimizer/memo.h
  src/include/optimizer/optimizer.h
  src/include/optimizer/rule.h
  src/optimizer/memo.cpp
  test/optimizer/column_stats_collector_test.cpp
  test/optimizer/cost_test.cpp
  test/optimizer/count_min_sketch_test.cpp
  test/optimizer/histogram_test.cpp
  test/optimizer/hyperloglog_test.cpp
  test/optimizer/old_optimizer_test.cpp
  test/optimizer/operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/optimizer_rule_test.cpp
  test/optimizer/optimizer_test.cpp
  test/optimizer/selectivity_test.cpp
  test/optimizer/stats_storage_test.cpp
  test/optimizer/table_stats_collector_test.cpp
  test/optimizer/table_stats_test.cpp
  test/optimizer/top_k_elements_test.cpp
  test/optimizer/tuple_sampler_test.cpp
  test/optimizer/tuple_samples_storage_test.cpp
Labels: accepted

#1238 Memory leak fixes for the unit tests
  test/optimizer/optimizer_rule_test.cpp
  test/planner/plan_util_test.cpp
Labels: accepted

#1235 Fix memory leak in the insert_sql_test [Partial fix for #1212]
  test/sql/insert_sql_test.cpp
Labels: accepted

#1231 Fix SSL test
  script/installation/create_certificates_test.sh
  src/network/peloton_server.cpp
  test/network/ssl/root.crt
  test/network/ssl/root.key
  test/network/ssl/root_test.crt
  test/network/ssl/server.crt
  test/network/ssl/server.key
  test/network/ssl/server_test.crt
  test/network/ssl/server_test.key
  test/network/ssl_test.cpp
Labels: ready_for_review
