Repository cmu-db/peloton, pull requests merged in 2018-04, with the labels that each got.

#1201 Doxygen comments for files in concurrency
  src/brain/modelgen/LSTM.pb
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/include/concurrency/decentralized_epoch_manager.h
  src/include/concurrency/epoch_manager.h
  src/include/concurrency/epoch_manager_factory.h
  src/include/concurrency/local_epoch.h
  src/include/concurrency/timestamp_ordering_transaction_manager.h
  src/include/concurrency/transaction_context.h
  src/include/concurrency/transaction_manager.h
  src/include/concurrency/transaction_manager_factory.h
Labels: ready_for_review

#1250 fix memory leaks
  src/brain/kd_tree.cpp
  src/include/brain/kd_tree.h
Labels: accepted, bug

#1247 Tensorflow memory leak fix
  src/brain/tf_session_entity/tf_session_entity.cpp
  test/leak_suppr.txt
Labels: accepted, bug

#1242 Fix 4 table join bug in binding iterator
  src/include/optimizer/operator_expression.h
  src/optimizer/binding.cpp
  src/optimizer/memo.cpp
  src/optimizer/operator_expression.cpp
  src/optimizer/operators.cpp
  src/optimizer/rule_impls.cpp
  test/sql/optimizer_sql_test.cpp
Labels: accepted

#1236 Junit updates
  script/testing/junit/.gitignore
  script/testing/junit/InsertPSTest.java
  script/testing/junit/Makefile
  script/testing/junit/PLTestBase.java
  script/testing/junit/UpdateTest.java
  src/settings/settings_manager.cpp
Labels: accepted

#1108 Support for EXPLAIN statement
  src/common/internal_types.cpp
  src/include/common/internal_types.h
  src/include/common/sql_node_visitor.h
  src/include/network/postgres_protocol_handler.h
  src/include/parser/explain_statement.h
  src/include/parser/parsenodes.h
  src/include/parser/postgresparser.h
  src/include/parser/statements.h
  src/network/postgres_protocol_handler.cpp
  src/parser/postgresparser.cpp
Labels: accepted

#1237 Insert plan changes
  script/testing/jdbc/README.md
  src/include/planner/insert_plan.h
  src/planner/insert_plan.cpp
Labels: accepted

#1221 Clean up Brain framework code
  src/include/brain/brain.h
  src/include/common/event_util.h
  src/include/common/notifiable_task.h
  src/main/peloton/peloton.cpp
  src/network/peloton_server.cpp
Labels: accepted

#1102 Allow setting number of GC threads from command line
  src/common/init.cpp
  src/include/common/exception.h
  src/include/settings/settings.h
  src/include/settings/settings_macro.h
  src/include/settings/settings_manager.h
  src/include/type/value.h
  src/main/peloton/peloton.cpp
  src/settings/settings_manager.cpp
Labels: accepted

#1265 Fix build failed issue for apple's clang 9.1 due to unused-lambda-capture error
  src/gc/transaction_level_gc_manager.cpp
  src/include/index/bwtree.h
  src/traffic_cop/traffic_cop.cpp
Labels: accepted

#1251 fix 'not a supported wheel on this platform' error when running package.sh on Ubuntu 17.10
  script/installation/packages.sh
Labels: accepted

#1266 Fixes the attribute reordering in update statements
  src/codegen/operator/update_translator.cpp
  test/sql/update_sql_test.cpp
Labels: accepted, bug

#1262 Parser: Add handling of type casts in expression
  src/parser/postgresparser.cpp
  test/parser/postgresparser_test.cpp
Labels: accepted, bug

#1264 Change travis configuration to run Address Sanitizer with gcc 5
  .travis.yml
Labels: accepted, build

#1276 BwTree non-unique key insert fix
  src/include/index/bwtree.h
  src/index/bwtree_index.cpp
  test/include/index/testing_index_util.h
  test/index/bwtree_index_test.cpp
  test/index/testing_index_util.cpp
Labels: accepted

#1278 Integrate junit tests into Travis and Jenkins
  .travis.yml
  Jenkinsfile
  script/installation/packages.sh
  script/testing/junit/InsertPSTest.java
  script/testing/junit/InsertTest.java
  script/testing/junit/Makefile
  script/testing/junit/Readme.txt
  script/testing/junit/build.xml
  script/testing/junit/run_junit.py
Labels: in progress

#1248 Workload Prediction
  cmake/Dependencies.cmake
  cmake/Modules/FindEigen3.cmake
  script/installation/packages.sh
  src/CMakeLists.txt
  src/brain/modelgen/LSTM.pb
  src/brain/modelgen/LSTM.py
  src/brain/modelgen/LSTM_Model.py
  src/brain/modelgen/model_generator.py
  src/brain/modelgen/settings.json
  src/brain/util/eigen_util.cpp
  src/brain/util/tf_session_entity/tf_session_entity.cpp
  src/brain/util/tf_session_entity/tf_session_entity_input.cpp
  src/brain/util/tf_session_entity/tf_session_entity_io.cpp
  src/brain/util/tf_session_entity/tf_session_entity_output.cpp
  src/brain/workload/base_tf.cpp
  src/brain/workload/lstm_tf.cpp
  src/brain/workload/workload_defaults.cpp
  src/include/brain/util/eigen_util.h
  src/include/brain/util/tf_session_entity/tf_session_entity.h
  src/include/brain/util/tf_session_entity/tf_session_entity_input.h
  src/include/brain/util/tf_session_entity/tf_session_entity_io.h
  src/include/brain/util/tf_session_entity/tf_session_entity_output.h
  src/include/brain/util/tf_util.h
  src/include/brain/workload/base_tf.h
  src/include/brain/workload/lstm_tf.h
  src/include/brain/workload/workload_defaults.h
  src/include/common/internal_types.h
  src/include/util/file_util.h
  test/brain/tensorflow_test.cpp
  test/leak_suppr.txt
Labels: accepted

#1301 IndexScanDesc and IndexScanPlan Refactoring
  src/catalog/abstract_catalog.cpp
  src/executor/hybrid_scan_executor.cpp
  src/executor/index_scan_executor.cpp
  src/include/executor/hybrid_scan_executor.h
  src/include/executor/index_scan_executor.h
  src/include/planner/hybrid_scan_plan.h
  src/include/planner/index_scan_plan.h
  src/main/sdbench/sdbench_workload.cpp
  src/main/tpcc/tpcc_delivery.cpp
  src/main/tpcc/tpcc_new_order.cpp
  src/main/tpcc/tpcc_order_status.cpp
  src/main/tpcc/tpcc_payment.cpp
  src/main/tpcc/tpcc_stock_level.cpp
  src/main/ycsb/ycsb_mixed.cpp
  src/optimizer/plan_generator.cpp
  src/planner/hybrid_scan_plan.cpp
  src/planner/index_scan_plan.cpp
  test/concurrency/testing_transaction_util.cpp
  test/executor/index_scan_test.cpp
  test/executor/join_test.cpp
  test/index/hybrid_index_test.cpp
Labels: ready_for_review

#1311 Jenkins update to gcc5
  .travis.yml
  CMakeLists.txt
  Jenkinsfile
Labels: build, in progress

#1271 Remove retry on close failure
  CMakeLists.txt
  src/common/utility.cpp
  src/include/common/utility.h
  src/network/connection_handle.cpp
  src/network/peloton_server.cpp
Labels: accepted

#1133 Move parse tree binding from optimizer to catalog
  src/catalog/abstract_catalog.cpp
  src/include/optimizer/abstract_optimizer.h
  src/include/optimizer/optimizer.h
  src/optimizer/optimizer.cpp
  src/traffic_cop/traffic_cop.cpp
  test/binder/binder_test.cpp
  test/executor/copy_test.cpp
  test/executor/create_index_test.cpp
  test/executor/delete_test.cpp
  test/executor/update_test.cpp
  test/optimizer/old_optimizer_test.cpp
  test/optimizer/optimizer_test.cpp
  test/planner/planner_equality_test.cpp
  test/sql/testing_sql_util.cpp
  test/statistics/testing_stats_util.cpp
Labels: accepted

#1324 Delete the unsed index_predicate_ in index scan plans.
  src/include/planner/hybrid_scan_plan.h
  src/include/planner/index_scan_plan.h
  src/planner/hybrid_scan_plan.cpp
  src/planner/index_scan_plan.cpp
Labels: ready_for_review

#1321 fix #1277 Socket bind failure handling
  src/main/peloton/peloton.cpp
  src/network/peloton_server.cpp
Labels: accepted
