Repository cmu-db/peloton, pull requests merged in 2018-05, with the labels that each got.

#1190 Mapping table fix to avoid preallocating memory
  src/include/index/bwtree.h
  src/index/bwtree_index.cpp
Labels: accepted

#1372 Update bwtree.h for issue #1351
  src/include/index/bwtree.h
Labels: accepted

#1375 Performance Fixes
  src/catalog/manager.cpp
  src/common/container/cuckoo_map.cpp
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_context.cpp
  src/include/catalog/manager.h
  src/include/common/container/cuckoo_map.h
  src/include/common/internal_types.h
  src/include/concurrency/transaction_context.h
Labels: ready_for_review

#1322 fix #1313 Remove read only isolation level
  src/common/internal_types.cpp
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_manager.cpp
  src/gc/transaction_level_gc_manager.cpp
  src/include/common/internal_types.h
  src/include/concurrency/transaction_context.h
  src/include/concurrency/transaction_manager.h
  test/common/internal_types_test.cpp
  test/concurrency/serializable_transaction_test.cpp
  test/include/concurrency/testing_transaction_util.h
Labels: accepted

#1379 Resolves Clang warnings and LLVM assertion failure on Mac
  src/codegen/code_context.cpp
  src/codegen/function_builder.cpp
  src/codegen/lang/vectorized_loop.cpp
  src/codegen/operator/table_scan_translator.cpp
  src/codegen/util/sorter.cpp
  test/codegen/hash_table_test.cpp
Labels: bug, ready_for_review

#1380 Performance Fixes: pass TileGroupHeader*, avoid RW set lookups
  src/codegen/transaction_runtime.cpp
  src/concurrency/timestamp_ordering_transaction_manager.cpp
  src/concurrency/transaction_context.cpp
  src/executor/hybrid_scan_executor.cpp
  src/executor/index_scan_executor.cpp
  src/executor/seq_scan_executor.cpp
  src/include/concurrency/timestamp_ordering_transaction_manager.h
  src/include/concurrency/transaction_manager.h
  src/storage/data_table.cpp
Labels: ready_for_review

#1333 Added more query cache test for binding tuple value expression
  test/codegen/query_cache_test.cpp
Labels: accepted
